name: Build Run and Test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use a specific version if needed

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard --CCN 3 src/main/

    - name: Build and Generate coverage
      run: mvn test jacoco:report

    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: ./target/site/jacoco
        retention-days: 21

    - name: Run Check Complete Script
      run: |
        chmod +x ./.github/workflows/check-complete.sh  # Make script executable
        bash ./.github/workflows/check-complete.sh       # Run the script
